import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Contacts from "@/components/Contacts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark:bg-black dark:text-white">
            <body className="font-ClashDisplayMedium overflow-x-hidden px-4">
                <header>
                    <Navbar />
                </header>
                {children}
                <footer className="mt-[500px] md:mt-80 lg:mt-96 xl:mt-52 pt-10 border-t border-black/20 dark:border-white/20">
                    <Contacts />
                </footer>
            </body>
        </html>
    );
}
